apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ainek2-poi-map-app-dev
  annotations:
    argocd/app-name: ainek2-poi-map-app-dev
    backstage.io/kubernetes-id: ainek2-poi-map-app
    backstage.io/kubernetes-namespace: ainek2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/ainek2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/ainek2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/ainek2/deployments/ainek2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/ainek2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ainek2-poi-map-app-ainek2.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ainek2"
  system: workshop-system-ainek2
  consumesApis:
    - gateway-api-ainek2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ainek2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ainek2"
